### ISSUE TITLE
Single text input field for project-level identifiers

### ISSUE THREAD

**Issue by pinin4fjords** [nf-core/fetchngs#120]
### Description of feature

In my current usage of this workflow I generally have a single SRP* project identifier, and I trigger the workflow in Tower.

It's a bit painful to have to write a CSV file for that single identifier and upload it to tower as a dataset before I trigger the workflow. 

Would you be amenable to a single string input for a project-level identifier (as an alternative to the file input)? I can take a crack at that if so.

**Comment by drpatelh** [comment]
I really like the idea of this but I wonder if it will cause more issues than it's worth. The `input` parameter is currently specified as being a `file-path` in the schema along with other corresponding settings like `mimetype`, `pattern` etc which wouldn't apply if we allow a comma-separated string of ids to be provided. The other option is to have another parameter specifically for these but that doesn't sit right either because `--input` is quite generic and should incorporate this.

**Comment by pinin4fjords** [comment]
Thanks- I'm mostly thinking about my Tower users in-house, and the extra steps needed to create and upload a file with the right extension etc just to supply that single identifier. Any suggestions as to a better workaround?

Maybe it would rather be a Tower feature request to be able to supply file contents as a text field?

**Comment by drpatelh** [comment]
Closing this as I think we will always need some sort of file input to the pipeline given we also want to use nf-validation to validate samples ids.
